# Стемы/ключевые слова для детекта тега.
# Можно использовать как подстроки (case-insensitive) или как regex.
triggers:
  fear_pain:
    - "боюсь"
    - "страшн"         # страшно/страшновато
    - "больн"          # больно/болит
    - "анестез"
    - "седац"
    - "замороз"
    - "комфорт"

  price:
    - "сколько"
    - "цена"
    - "стоим"
    - "дорог"
    - "прайс"
    - "акци"
    - "рассроч"
    - "бюджет"

  duration:
    - "сколько времени"
    - "срок"
    - "за сколько"
    - "долго"
    - "когда"
    - "этап"

  indications:
    - "подойд"
    - "показан"
    - "противопоказ"
    - "риски"
    - "можно ли"
    - "подходит"

  doctor:
    - "врач"
    - "доктор"
    - "к кому"
    - "специалист"
    - "имплантолог"
    - "хирург"
    - "записаться к"

  warranty:
    - "гаранти"
    - "не прижив"
    - "осложнен"
    - "перестав"
    - "передел"

  tomography:
    - "кт"
    - "томограф"
    - "томографи"
    - "рентген"
    - "панорам"
    - "снимок"
    - "3d"

  bad_experience:
    - "плохой опыт"
    - "неудач"
    - "передел"
    - "разочар"
    - "ошибк"
    - "жалоб"

# Необязательные правила подавления опенера:
suppress_rules:
  price:
    when_answer_contains_numbers: true   # если в ответе есть конкретные цены — используем bridges вместо опенера
