# config/empathy_triggers.yaml — словари триггеров
# Используются для эвристического определения эмоции по ключевым словам.
# Вопрос пользователя → ищем совпадение → подгружаем нужный блок из empathy.yaml.

pain:
  - "больно"
  - "страш"
  - "анестез"
  - "обезбол"
  - "заморозк"
  - "болезн"

price:
  - "цена"
  - "стоим"
  - "дорог"
  - "дешев"
  - "вычет"
  - "рассроч"
  - "скидк"
  - "прайс"

trust:
  - "врач"
  - "специал"
  - "квалифик"
  - "опыт"
  - "отзыв"
  - "команда"
  - "довер"
  - "ошибк"

consultation:
  - "консультац"
  - "прием"
  - "осмотр"
  - "первый визит"
  - "сколько длит"
  - "как проходит"

osseointegration:
  - "прижив"
  - "отторж"
  - "не приметс"
  - "не приживет"
  - "оссео"
  - "интеграц"

safety:
  - "стерил"
  - "инфекц"
  - "зараж"
  - "чисто"
  - "безопас"
  - "одноразов"
  - "кварц"
